name: ROS2 Jazzy

on:
  workflow_run:
    workflows: ["Pre-commit"]
    types: [completed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      # Set up ROS
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      # Run ROS CI
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: plotjuggler_ros
          target-ros2-distro: jazzy
